/*
Agrega2 es una federación de repositorios de objetos digitales educativos formada por todas las Comunidades Autónomas propiedad de Red.es.

This program is free software: you can redistribute it and/or modify it under the terms of the European Union Public Licence (EUPL v.1.0).  This program is distributed in the hope that it will be useful,  but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the European Union Public Licence (EUPL v.1.0). You should have received a copy of the EUPL licence along with this program.  If not, see http://ec.europa.eu/idabc/en/document/7330.
*/
// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package es.pode.publicacion.negocio.monitor;

/**
 * <p>
 * Se trata del objeto de valor que contiene los valores que
 * indican si una tarea esta permitida o no y las causas de la
 * negativa.
 * </p>
 */
public class PermisoTareaVO
    implements java.io.Serializable
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -1734838687337063832L;

	/**
     * Constructor por defecto
     */        
    public PermisoTareaVO()
    {
    }

    /**
     * Constructor taking all properties.
     * @param idResultado  Identificador del resultado de la petición de realización de la tarea.
     * @param descripcion  Descripción del error por la que se deniega el permiso a ejecutar una tarea.
     */
    public PermisoTareaVO(
        java.lang.String idResultado,
        java.lang.String descripcion)

    {
        this.idResultado = idResultado;
        this.descripcion = descripcion;
    }

    /**
     * Copies constructor from other PermisoTareaVO
     * @param otherBean PermisoTareaVO 
     */
    public PermisoTareaVO(PermisoTareaVO otherBean)
    {
        if (otherBean != null)
        {
            this.idResultado = otherBean.getIdResultado();
            this.descripcion = otherBean.getDescripcion();
        }
    }

    private java.lang.String idResultado;

    /**
     * <p>
     * Identificador del resultado de la petición de realización de la
     * tarea.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getIdResultado()
    {
        return this.idResultado;
    }

    /**
   * <p>
   * Identificador del resultado de la petición de realización de la
   * tarea.
   * </p>
     *  @param idResultado  Identificador del resultado de la petición de realización de la tarea.  
     */
    public void setIdResultado(java.lang.String idResultado)
    {
        this.idResultado = idResultado;
    }

    private java.lang.String descripcion;

    /**
     * <p>
     * Descripción del error por la que se deniega el permiso a
     * ejecutar una tarea.
     * </p>
     * @return java.lang.String
     */
    public java.lang.String getDescripcion()
    {
        return this.descripcion;
    }

    /**
   * <p>
   * Descripción del error por la que se deniega el permiso a
   * ejecutar una tarea.
   * </p>
     *  @param descripcion  Descripción del error por la que se deniega el permiso a ejecutar una tarea.  
     */
    public void setDescripcion(java.lang.String descripcion)
    {
        this.descripcion = descripcion;
    }

}