cp dependencias/*.jar apache-tomcat-5.5.26/webapps/fuentestaxonomicas-1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/validador-1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/modificador-1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/ModificadorWeb/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/entregar-1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/visualizador-1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/catalogacion-1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/catalogadorWeb/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/empaquetadorbasico-F1/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/PortalEmpaquetador/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/herramientaoffline/WEB-INF/lib
cp dependencias/*.jar apache-tomcat-5.5.26/webapps/localizador-1/WEB-INF/lib